### PR TITLE
Add py.typed file

### PR DESCRIPTION
**Pull request by adriangb**
This fix the typical "no stub file found" errors from Pylance and MyPy

### CODE REVIEW

**Comment by RobertoPrevato** [comment]
Thank You @adriangb - I was just doing the same for `GuardPost` yesterday. Isn't it necessary to also add the `py.typed` file to a MANIFEST.in file (for example), so that it gets included in the distribution package?

**Comment by adriangb** [comment]
Oh yep. I'm used to using `poetry`/`pyproject.toml` so I forgot about that 😅

**Comment by RobertoPrevato** [comment]
The build failed, but this seems to be an issue within `black` - please don't mind about this right now. I'll pin the dependency.

**Comment by RobertoPrevato** [comment]
I'll merge your PR anyway, then I'll take a look at the GH Workflow. 😄 
At the moment I don't have time.

**Comment by adriangb** [comment]
All good. I added the file to the `setup.py`; I tested locally and it works for me.

**Comment by RobertoPrevato** [comment]
Thank you for your help 🚀

**Comment by adriangb** [comment]
np!

**Pull request merged**
